# Generated by Django 4.1.6 on 2023-02-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
